Models/CardType.cs
namespace Hotwired.Models
{
    public class CardType
    {
        public int Id
        {
            get; set;
        }
        public bool IsVisit
        {
            get; set;
        }

        public bool ForcedLocation
        {
            get; set;
        }
        public bool IsUserAccount
        {
            get; set;
        }
        public string Descr
        {
            get; set;
        }
    }
}

Pages/CardType.cshtml.cs
using Hotwired.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hotwired.Pages
{
    public class CardTypeModel : PageModel
    {
       
        public void OnGet()
        {
            
        }
    }
}

Pages/Error.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System.Diagnostics;

namespace Hotwired.Pages
{
    [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
    [IgnoreAntiforgeryToken]
    public class ErrorModel : PageModel
    {
        public string? RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);

        private readonly ILogger<ErrorModel> _logger;

        public ErrorModel(ILogger<ErrorModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier;
        }
    }
}

Pages/Home.cshtml.cs
using Hotwired.Models;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hotwired.Pages
{
    public class HomeModel : PageModel
    {
       
        public List<CardType> CardTypes { get; set; }
        public void OnGet()
        {
            CardTypes = new List<CardType>();
        }
        public PartialViewResult OnGetCardTypes()
        {
            return Partial("CardType");
        }
        public PartialViewResult OnGetAddType()
        {
            var type = new CardType { Id = 0, Descr = String.Empty, IsVisit = false, IsUserAccount = false, ForcedLocation = false };
            return Partial("CardTypeAddEdit", type);
        }
        public PartialViewResult OnPostSaveType(int id, string descr, bool isVisit, bool isUserAccount, bool forcedLocation)
        {
            if (id == 0)
            {
                var type = new CardType { Id = Types.Instance.Count + 1, Descr = descr, IsVisit = isVisit, ForcedLocation = forcedLocation, IsUserAccount = isUserAccount };
                Types.Instance.Add(type);
                Response.ContentType = "text/vnd.turbo-stream.html";
                return Partial("CardTypeAdd",type);
            }
            else
            {
                var type = Types.Instance.Where(i => i.Id == id).FirstOrDefault();
                type.Descr = descr;
                type.IsVisit = isVisit;
                type.IsUserAccount = isUserAccount;
                type.ForcedLocation = forcedLocation;
                Response.ContentType = "text/vnd.turbo-stream.html";
                return Partial("CardTypeEdit", type);
            }
            
        }

        public PartialViewResult OnGetEditType(int id)
        {
            var type = Types.Instance.Where(i => i.Id == id).FirstOrDefault();
            return Partial("CardTypeAddEdit", type);
        }

        public PartialViewResult OnPostDeleteType(int id)
        {
            var type = Types.Instance.Where(i => i.Id == id).FirstOrDefault();
            Types.Instance.Remove(type);

            Response.ContentType = "text/vnd.turbo-stream.html";
            return Partial("CardTypeDelete", type);
        }
    }
    public class Types : List<CardType>
    {
        private Types() { }
        private static List<CardType> _Instance = null;
        public static List<CardType> Instance
        {
            get
            {
                if (_Instance == null)
                {
                    _Instance = new List<CardType>();
                }
                return _Instance;
            }
        }
    }
}

Pages/Index.cshtml.cs
using System.Net.Mail;
using System.Security.Principal;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hotwired.Pages
{
    public class IndexModel : PageModel
    {
        private readonly ILogger<IndexModel> _logger;
        public string UserName { get; set; }
        public string Password { get; set; }
        public IndexModel(ILogger<IndexModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
            
        }
        public IActionResult OnPost()
        {
            if(!String.IsNullOrEmpty(UserName) || !String.IsNullOrEmpty(Password))
            {
                ViewData["Message"] = "Lutfen eksik bilgi girmeyiniz";
                
                return Page();
            }else
            {
                return new RedirectToPageResult("Home");
            }
        }
    }
}

Pages/Privacy.cshtml.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;

namespace Hotwired.Pages
{
    public class PrivacyModel : PageModel
    {
        private readonly ILogger<PrivacyModel> _logger;

        public PrivacyModel(ILogger<PrivacyModel> logger)
        {
            _logger = logger;
        }

        public void OnGet()
        {
        }
    }
}

Pages/CardType.cshtml
@page
@model Hotwired.Pages.HomeModel
@{
    Layout = "_Layout";
}
<turbo-frame id="content">
    <div class="flex h-screen justify-center items-center">
        <div class="w-96 h-2/3 border border-black">
            <div class="p-2 h-10 w-full flex justify-between border-b border-black">
                <span class="justify-start">Kart Tipleri</span>
                <a asp-page="/Home" asp-page-handler="AddType" data-turbo-frame="type-0" class="justify-end">
                    +
                </a>
            </div>
            <div class="border border-black m-4 p-4">
                <div class="grid grid-cols-3 gap-4">
                    <span>Tanım</span>
                    <span>Ziyaret Edilebilir</span>
                    <span></span>
                </div>
                <turbo-frame id="type-0"></turbo-frame>
                <turbo-frame id="card-types">
                    @foreach (var type in Types.Instance) {
                        <partial name="CardTypeView" model="@type"></partial>
                    }
                </turbo-frame>
            </div>
        </div>

    </div>
</turbo-frame>
@*<turbo-frame id="first-frame">


    <div class="grid grid-cols-12 ">
        <div class="col-span-1"></div>

        <div class="col-span-10 mt-5">
            <div class="border border-black">
                    <div class="grid grid-cols-12 text-center">

                        <div class="col-span-4 pb-5">
                            <h4>Tanımlar</h4>
                        </div>

                        <div class="col-span-4 pb-5">
                            <h4>Ziyaret Edilebilir</h4>
                        </div>

                        <div class="col-span-4"></div>

                        <div class="col-span-4 mb-3">
                            <p></p>
                        </div>

                        <div class="col-span-4">
                            <input type="checkbox">
                        </div>

                        <div class="col-span-4">
                            <a asp-page="EditCard" asp-route-message="">/</a>
                        </div>

                    </div>
            </div>
        </div>
        <div class="col-span-1"></div>
    </div>

 </turbo-frame>*@

Pages/CardTypeAdd.cshtml
@model Hotwired.Models.CardType
<turbo-stream action="replace" target="type-0">
    <template>
        <turbo-frame id="type-0"></turbo-frame>
    </template>

</turbo-stream>

<turbo-stream action="append" target="card-types">
    <template>
        <partial name="CardTypeView" model="@Model"></partial>
    </template>

</turbo-stream>

Pages/CardTypeAddEdit.cshtml
@model Hotwired.Models.CardType
<turbo-frame id="type-@Model.Id">
    <form method="post" >
        <input type="hidden" asp-for="@Model.Id" hidden />
        <div class="grid grid-cols-3 py-3">
            <input asp-for="@Model.Descr" />
            <a asp-page="/Home" class="text-center ml-2">x</a>
            <button asp-page="/Home" asp-page-handler="SaveType" asp-route-id="@Model.Id" class="button-primary ml-2">
                <svg xmlns="http://www.w3.org/2000/svg" class="h-6 w-6" fill="none" viewBox="0 0 24 24" stroke="currentColor" stroke-width="2">
                    <path stroke-linecap="round" stroke-linejoin="round" d="M8 7H5a2 2 0 00-2 2v9a2 2 0 002 2h14a2 2 0 002-2V9a2 2 0 00-2-2h-3m-1 4l-3 3m0 0l-3-3m3 3V4" />
                </svg>
            </button>
        </div>
        <div class="grid grid-cols-2">
          <span>Ziyaret Edilebilir</span>
          <input asp-for="@Model.IsVisit" name="isVisit" type="checkbox" />
          <span>Lokasyon Zorunlu</span>
          <input asp-for="@Model.ForcedLocation" name="forcedLocation" type="checkbox" />
          <span>Kullanıcı Hesabı</span>
          <input asp-for="@Model.IsUserAccount" name="isUserAccount" type="checkbox" />
        </div>
    </form>
</turbo-frame>

Pages/CardTypeEdit.cshtml
@*
    For more information on enabling MVC for empty projects, visit https://go.microsoft.com/fwlink/?LinkID=397860
*@
@{
}
@model Hotwired.Models.CardType

<turbo-stream action="replace" target=@("type-" + Model.Id)>
  <template>
    <partial name="CardTypeView.cshtml" model="@Model" />
  </template>
</turbo-stream>

Pages/CardTypeView.cshtml
@model Hotwired.Models.CardType


<turbo-frame id="type-@Model.Id">
    <div class="grid grid-cols-3 py-3 items-baseline">
        <span class="text-left">@Model.Descr</span>
        <input type="checkbox" checked ="@Model.IsVisit" disabled/> 
        <a asp-page="/Home" asp-page-handler="EditType" asp-route-id="@Model.Id" class="">
            <svg xmlns="http://www.w3.org/2000/svg" class="h-5 w-5" viewBox="0 0 20 20" fill="currentColor">
                <path d="M13.586 3.586a2 2 0 112.828 2.828l-.793.793-2.828-2.828.793-.793zM11.379 5.793L3 14.172V17h2.828l8.38-8.379-2.83-2.828z" />
            </svg>
        </a>
    </div>
</turbo-frame>

Pages/Home.cshtml
@page
@model Hotwired.Pages.HomeModel
<turbo-frame id="content">
    <div asp-page="/CardType" class="w-full h-50 border border-b-black">
        <div class="flex items-center m-3">
            <img class="pl-3 items-center" src="~/dist/images/idesse-symbol.svg" />
            <a asp-page="/Home" asp-page-handler="CardTypes" data-turbo-action="visit" class="pl-3">Kart Tipleri</a>
        </div>
    </div>
</turbo-frame>

Pages/Index.cshtml
@page
@model IndexModel
<div class="translate-y-40 justify-center flex top-50 left-50">
<div class="max-w-sm w-auto h-auto rounded overflow-hidden shadow-lg">
    <form method="post">
    <div class="px-6  py-4">
       <img class="w-full object-cover " src="~/dist/images/idesse_logo.svg"/>
       <div class="flex pt-3 w-full justify-center items-center">
        <p class="pr-2 ">UserName:</p>
            <input asp-for="@Model.UserName" type="email" />
       </div>
       <div class="flex w-full pt-3 justify-center items-center">
        <p class="pr-4">Password:</p>
            <input asp-for="@Model.Password" type="password" />
       </div>
    </div>
    
    <div class="px-6 float-right pt-4 pb-2">
        <button type="submit" asp-page="Index" class="bg-blue-700 hover:bg-gray-100 hover:text-blue-700 transition-all text-white font-semibold py-2 px-4 border border-gray-400 rounded shadow">
             Login
        </button>
    </div>
   
    </form>
</div>
</div>

Pages/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>Hotwired Ödev</title>
      <script src="~/dist/app.js" defer ></script>
        <link rel="stylesheet" href="~/dist/app.css" />
</head>
<body class="p-3 bg-white">
   
    <div >
        <main role="main" class="pb-3 ">
            @RenderBody()
        </main>
    </div>
  @if (ViewData["Message"] != null)
    {
        <script type="text/javascript">
            window.onload = function () {
                alert("@ViewData["Message"]");
            };
        </script>
    }
</body>
</html>